{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."music-grabber" = {
    image = "g33kphr33k/musicgrabber:latest";
    environment = {
      "DB_PATH" = "/data/music_grabber.db";
      "DEFAULT_CONVERT_TO_FLAC" = "true";
      "ENABLE_MUSICBRAINZ" = "true";
      "MUSIC_DIR" = "/music";
    };
    volumes = [
      "/home/simaolavos/data:/data:rw"
      "/var/lib/navidrome/music:/music:rw"
    ];
    ports = [
      "38274:8080/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=music-grabber"
      "--network=musicgrabber_default"
      "--shm-size=2147483648"
    ];
  };
  systemd.services."docker-music-grabber" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-musicgrabber_default.service"
    ];
    requires = [
      "docker-network-musicgrabber_default.service"
    ];
    partOf = [
      "docker-compose-musicgrabber-root.target"
    ];
    wantedBy = [
      "docker-compose-musicgrabber-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-musicgrabber_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f musicgrabber_default";
    };
    script = ''
      docker network inspect musicgrabber_default || docker network create musicgrabber_default
    '';
    partOf = [ "docker-compose-musicgrabber-root.target" ];
    wantedBy = [ "docker-compose-musicgrabber-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-musicgrabber-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
  networking.firewall.allowedTCPPorts = [ 38274 ];
}
